# Generated by Django 6.1.1 on 2026-09-19 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='materials.material'),
        ),
    ]
